services:
    source_postgres:
        image: postgres:15
        ports:
            - 5432:5432
        networks:
            - container_network
        environment:
            POSTGRES_DB: "source_db"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "secret"
        volumes:
            - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d source_db"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
    target_postgres:
        image: postgres:15
        ports:
            - 5434:5432
        networks:
            - container_network
        environment:
            POSTGRES_DB: "target_db"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "secret"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d target_db"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
    extract_load_transform:
        build:
            context: ./scripts
            dockerfile: Dockerfile
        networks:
            - container_network
        command: ["python", "extract_load_transform.py"]
        depends_on:
            source_postgres:
                condition: service_healthy
            target_postgres:
                condition: service_healthy

networks:
    container_network:
        driver: bridge
